language: generic
sudo: required
dist: trusty

# LLVM takes awhile to check out and otherwise we'll manage the submodules in
# our configure script, so disable auto submodule management.
git:
  submodules: false

# Install dependencies
addons:
    apt:
        sources:
            - llvm-toolchain-trusty-3.7
        packages:
            - curl
            - make
            - g++
            - python2.7
            - git
            - zlib1g-dev
            - libedit-dev
            - llvm-3.7-tools

before_install:
  - echo 0 | sudo tee /proc/sys/net/ipv6/conf/lo/disable_ipv6

script:
  - ./configure --llvm-root=/usr/lib/llvm-3.7
  - make tidy && make check-notidy -j4

# Real testing happens on http://buildbot.rust-lang.org/
#
# See https://github.com/rust-lang/rust-buildbot
#     CONTRIBUTING.md#pull-requests

notifications:
  email: false

branches:
  only:
    - master
